### ISSUE TITLE
String formatting error in PEFile.py module

### ISSUE THREAD

**Issue by awest1339** [MITRECND/multiscanner#25]
* CentOS Linux release 7.3.1611 (Core)
* Python 3.6.0

Actual behavior:
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/opt/multiscanner/multiscanner.py", line 100, in run
self.ret = self.__target(*self.__args, **self.__kwargs)
File "/opt/multiscanner/multiscanner.py", line 257, in _runModule
results = mod.scan(filelist, conf=conf)
File "/opt/multiscanner/modules/Metadata/PEFile.py", line 56, in scan
result['pehash'] = _get_pehash(pe)
File "/opt/multiscanner/modules/Metadata/PEFile.py", line 122, in _get_pehash
stk_size_bits = string.zfill(stk_size.bin, 32)
AttributeError: module 'string' has no attribute 'zfill'
```

Expected behavior:
* Not throwing this error

**Comment by awest1339** [comment]
Additional Error:
```python
Traceback (most recent call last):
File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/opt/multiscanner/multiscanner.py", line 100, in run
self.ret = self.__target(*self.__args, **self.__kwargs)
File "/opt/multiscanner/multiscanner.py", line 257, in _runModule
results = mod.scan(filelist, conf=conf)
File "/opt/multiscanner/modules/Metadata/PEFile.py", line 63, in scan
result['import_hash'] = pe.get_imphash()
File "/usr/local/lib/python3.6/site-packages/pefile.py", line 3623, in get_imphash
parts = libname.rsplit('.', 1)
TypeError: a bytes-like object is required, not 'str'
```
